name: Release

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: build
        env:
          CI_DONDE_RELEASE_VERSION: ${{ steps.extract_branch.outputs.branch }}
        run: |
          python -m pip install -U build setuptools wheel twine
          python -m build
      - name: publish
        env:
          TWINE_USERNAME: ${{ secrets.TESTPYPI_API_USER }}
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
        run: |
          python -m twine upload --repository testpypi dist/*
